import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { ReactElement } from 'react'
import Layout from 'components/layout'
import NestedLayout from 'components/nested-layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      {/* 使用Link代替a标签，a会发起http请求Link不会发起http请求。 */}
      <Link href="/post">to Post</Link>
      <Link href="/post/1">to Post/1</Link>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

Home.getLayout = (page: ReactElement) => {
  return (
    <Layout>
      <NestedLayout />
      {page}
    </Layout>
  )
}